apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-config
  labels:
    {{- include "travel-chart.labels" . | nindent 4 }}
data:
  REACT_APP_ENV: {{ .Values.env.environment | quote }}
  REACT_APP_API_URL: {{ .Values.env.apiUrl | quote }}