# ServiceAccount = Identity for a Pod (like IAM User for Pod)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: travel-readonly-sa
  namespace: travel-helm
---
# Role = What you can do, but ONLY in ONE namespace (travel-helm)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: travel-helm
rules:
- apiGroups: [""] # "" = core API (pods, services)
  resources: ["pods"] # only pods
  verbs: ["get", "list"] # can only read, not create/delete - principle of least privilege
---
# RoleBinding = Glue SA + Role together (like attaching policy to user)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: travel-helm
subjects:
- kind: ServiceAccount
  name: travel-readonly-sa
  namespace: travel-helm
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
