apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "travel-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  REACT_APP_MAPS_API_KEY: {{ .Values.secret.mapsApiKey | quote }}
