apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: travel-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/promiseopah/Travel-Explore-React-App
    targetRevision: main
    path: [STRIPPED 92 bytes]:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: travel-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
