replicaCount: 3
image:
     repository: 842746302640.dkr.ecr.us-east-1.amazonaws.com/travel-app
  tag: b5eb9a43156a7a9aebd5d62fb2683d7b3c22a374
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: travel.prod.example.com
      paths:
        - path: /
          pathType: Prefix

config:
  NODE_ENV: production
  API_URL: https://api.prod.example.com

# Production ESO + IRSA
serviceAccount:
  name: travel-s3-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/travel-app-prod-s3-role

secretStore:
  provider: aws
  region: us-east-1
